fix: close assigned issue logic
devpool-directory/devpool-directory pull request #1157
Opened 2024-03-27 12:18 UTC by Ekep-Obasi

### Task

closes: [#23](https://github.com/ubiquity/devpool-directory-bounties/issues/23), 

### Solution

I realized that the existing logic for closing assigned issues works correctly but while updating issue always reopens the issue again

```js 
        if (
          devpoolIssue.title !== projectIssue.title ||
          devpoolIssue.state !== projectIssue.state || // <-- since the states are different, if block runs
          (!isDevpoolUnavailableLabel && projectIssue.assignee?.login) ||
          (isDevpoolUnavailableLabel && !projectIssue.assignee?.login) ||
          devpoolIssue.body !== projectIssue.html_url ||
          devpoolIssueLabelsStringified !== projectIssueLabelsStringified
        ) {
          await octokit.rest.issues.update({
            owner: DEVPOOL_OWNER_NAME,
            repo: DEVPOOL_REPO_NAME,
            issue_number: devpoolIssue.number,
            title: projectIssue.title,
            body,
            state: projectIssue.state as "open" | "closed", // <--- projectIssue state is set back to "open"
            labels: getDevpoolIssueLabels(projectIssue, projectUrl),
          });
          console.log(`Updated: ${devpoolIssue.html_url} (${projectIssue.html_url})`);
        } else {
          console.log(`No updates: ${devpoolIssue.html_url} (${projectIssue.html_url})`);
        }
``` 

You can see this behaviour on this [issue](https://github.com/ubiquity/devpool-directory/issues/1154) or on the screenshot below

![evidence](https://github.com/ubiquity/devpool-directory/assets/117433403/b6e32f0c-b215-4908-8b97-22a9f8a89f29)

### Change 

- [x] refactored the logic that updates issue

```js 
state: !isDevpoolUnavailableLabel ? (projectIssue.state as "open" | "closed") : "closed",
``` 

- [x] added tests to assert that current functionality (closing of assigned issues) works properly

![work ubi test](https://github.com/ubiquity/devpool-directory/assets/117433403/d6499ad3-bf66-42c4-89cc-ec1b7b3161a3)

2024-03-27 21:08 UTC, rndquu requested changes
The issue persists

Current behaviour when project issue is assigned and devpool issue is open:
- 1st `index.ts` run closes devpool issue
- 2nd `index.ts` run opens devpool issue
- 3rd (and all other) `index.ts` run closes devpool issue

2024-04-01 12:12 UTC, gentlementlegen commented
After locally testing, the test `test` fails with the following state
```JSON
Error: expect(received).toMatchObject(expected)

- Expected  - 3
+ Received  + 9

@@ -22,11 +22,11 @@
        "subscriptions_url": "",
        "type": "",
        "url": "",
      },
      "author_association": "NONE",
-     "body": "body",
+     "body": "https://github.com/ubiquity/test-repo/issues/1",
      "closed_at": null,
      "comments": 0,
      "comments_url": "",
      "created_at": "",
      "events_url": "",
@@ -35,23 +35,29 @@
      "labels": Array [
        Object {
          "name": "Pricing: 200 USD",
        },
        Object {
-         "name": "Time: 1h",
+         "name": "Partner: ubiquity/test-repo",
        },
        Object {
          "name": "id: 1",
+       },
+       Object {
+         "name": "Unavailable",
        },
+       Object {
+         "name": "Time: 1h",
+       },
      ],
      "labels_url": "",
      "locked": false,
      "milestone": null,
      "node_id": "1",
      "number": 1,
      "repository_url": "https://github.com/ubiquity/devpool-directory",
-     "state": "closed",
+     "state": "open",
      "title": "issue",
      "updated_at": "",
      "url": "",
      "user": null,
    },
```

2024-04-01 12:13 UTC, gentlementlegen requested changes

2024-04-01 12:13 UTC, gentlementlegen commented on tests/main.test.ts
> +    const devpoolIssue = await getAllIssues(DEVPOOL_OWNER_NAME, DEVPOOL_REPO_NAME);
```suggestion
    const devpoolIssues = await getAllIssues(DEVPOOL_OWNER_NAME, DEVPOOL_REPO_NAME);
```

2024-04-04 08:12 UTC, Ekep-Obasi commented
I'm closing this PR, I think this issue had already been solved by @rndquu

2024-04-04 08:12 UTC, closed without merging