Prevent Unauthorized Users from creating issues in devpool
devpool-directory/devpool-directory pull request #1330
Opened 2024-08-21 00:21 UTC by jordan-ae

Resolves [#31](https://github.com/ubiquity/devpool-directory-bounties/issues/31)

This pull request introduces enhancements  preventing unauthorized bots from creating issues in the devpool-directory repository. Specifically, it implements a mechanism to detect and close issues created by entities that are not authorized, based on their association with our approved GitHub organizations.

**Key Changes:**

**Authorization Check for Issue Creation:**
 - Implemented a check to ensure that only bots associated with our approved GitHub organizations (ubiquity,                            ubiquibot,    or     UbiquityOS)     can    create issues.
- Unauthorized bots are blocked from creating issues, enhancing the security and integrity of the repository.

**Issue Closure for Unauthorized Attempts:**
- Attempted to delete unauthorized issues programmatically, but since GitHub doesn't provide an endpoint for this, I explored alternative solutions. 
-  After trying a bash script shared by @Keyrxng , which claims to enable programmatic deletion of GitHub issues, I was unable to make it work successfully.
 - As a fallback, unauthorized issues are now closed immediately to prevent them from polluting the repository.

 **Workflow Testing:**
Conducted a workflow QA run to test the closing of unauthorized issues:
 [Workflow QA Run](https://github.com/jordan-ae/devpool-directory/actions/runs/10480410296/job/29027995780)
 [Closed Unauthorized Issue](https://github.com/jordan-ae/devpool-directory/issues/71)

To make this workflow run possible, I temporarily disabled the check for unauthorized users when creating an issue. Under normal circumstances, this check should prevent unauthorized bots from creating issues altogether.

2024-08-21 00:56 UTC, Keyrxng commented
@jordan-ae tests have failed

If it's not possible to delete issues via a github cli script and we must rely on closing issues then you will have to verify that those closed issues are not affecting the statistics calculations.

I don't think the `state_reason` matters within the devpool especially if you verify stats are not affected.

I see that all of your issues have been closed in your forked `devpool-directory` which is going to make life difficult for future development if all issues are immediately closed in forks. This should be handled elegantly similar to how we handle spam links by checking if it's a fork

2024-08-21 01:07 UTC, Keyrxng commented
I can delete issues from my `devpool-directory` using the GH cli no problem @jordan-ae 

![image](https://github.com/user-attachments/assets/c2161f80-7f1c-42ab-bfde-1e64d1b55c9b)

2024-08-21 01:12 UTC, jordan-ae commented
@Keyrxng i attempt to do do several times during the day unsuccessfully. I'll try again first thing tomorrow morning

2024-08-21 01:20 UTC, Keyrxng commented
While the spec does not note that this should all be handled as a cron job the original implementation did exist in this form and I believe that's what's expected to be the case still. @rndquu @0x4007 can you confirm?

2024-08-21 21:40 UTC, jordan-ae commented
@Keyrxng I've given deleting issues a try again and still not been able to do so programmatically. The flag to delete without confirmation doesn't bypass github's restriction. Here's the authorization error that keeps popping up. I've bumped up my bot permission to have `repository: read & write permissions` but it still requires comfirmation

![Screenshot from 2024-08-21 22-36-20](https://github.com/user-attachments/assets/4cc61225-6175-4f35-9c7e-4f5ab4c8f1c0)

```
 - name: Close Unauthorized Issues
        run: |
          REPO="jordan-ae/devpool-directory"
          AUTHORIZED_ORG_IDS=(76412717 133917611 165700353)
          
          # Fetch issues with author login and author association (organization info might be absent)
          issues=$(gh issue list --repo "$REPO" --limit 100 --json number,author,title)

          # Check if issues JSON is valid
          if [[ -z "$issues" || "$issues" == "[]" ]]; then
            echo "No issues found or invalid JSON."
            exit 0
          fi
          
          # Process each issue
          echo "$issues" | jq -c '.[]' | while read -r issue; do
            issue_number=$(echo "$issue" | jq -r '.number')
            issue_author_login=$(echo "$issue" | jq -r '.author.login')
            issue_title=$(echo "$issue" | jq -r '.title')
            author_association=$(echo "$issue" | jq -r '.authorAssociation')
      
            if [[ ! " ${AUTHORIZED_ORG_IDS[@]} " =~ " ${issue_author_login} " && "$author_association" != "OWNER" ]]; then
              echo "Closing unauthorized issue: #$issue_number $issue_title (by $issue_author_login)..."
              gh issue delete "$issue_number" --repo "$REPO" --yes
            fi
          done 
```

2024-08-22 00:03 UTC, Keyrxng commented
@jordan-ae I'm not certain but it's likely your token/permissions. If that's the standard runner token that's being used it won't have admin rights to the org, you may have to pass a custom token.

I'd have went the way of writing it in TS personally as I'd find it easier to debug but that's just my preference. 

> I've bumped up my bot permission to have repository: read & write permissions but it still requires comfirmation

It's not your bot token that's being used I don't think it looks like it's the standard runner/repo token. Have you tried it with a PAT which has admin rights to the org where the issues exist?

2024-08-22 02:40 UTC, jordan-ae commented
Btw @Keyrxng & @rndquu  is it okay to make this feature a workflow with a cron job like the `sync-issues.yml` ?

2024-08-22 09:09 UTC, Keyrxng commented
> Btw @Keyrxng & @rndquu is it okay if I add a `delete unauthorized issues ` step to the `sync-issues.yml` workflow ? That will basically on workflow run get rid of any issues that haven't been created by an authorized entity without ever having to sync them in. Like in this [run](https://github.com/jordan-ae/devpool-directory/actions/runs/10501860020/job/29092533807)

I guess it can be either a step in the workflow or included in the Typescript logic. I'd prefer it built with TS but I wouldn't prevent merging for that reason.

Whatever way you choose to handle it, you need to consider the fact that other contributors after forking the devpool and running your workflow will automatically have all issues deleted which would make life difficult for future development. So this should be handled elegantly the same way we did with spam links.

2024-08-22 12:12 UTC, Keyrxng commented
- https://github.com/ubiquity/devpool-directory/issues/1334

@rndquu can you delete the two issues created from jordans bot?

2024-08-23 10:58 UTC, 0x4007 commented on scripts/delete-unauthorized-issues.sh
> +    if [[ ! " ${AUTHORIZED_ORG_IDS[@]} " =~ " ${issue_author_login} " && "$author_association" != "OWNER" ]]; then
I assume this is only for bots. I suppose thats fine because humans shouldn't open issues here anyways.

2024-08-23 11:27 UTC, 0x4007 requested changes

2024-08-23 11:27 UTC, 0x4007 commented on .github/workflows/sync-issues.yml
> +         GH_TOKEN: ${{ secrets.PAT }}
Please don't do this with having to add an extra secret PAT when we already have a bot auth token from the previous step. Use the bot auth and I can merge this in. 

```
      - name: Get GitHub App token
        uses: tibdex/github-app-token@v1.7.0
        id: get_installation_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
```

2024-08-23 11:29 UTC, 0x4007 commented on .github/workflows/sync-issues.yml
> +         GH_TOKEN: ${{ secrets.PAT }}
Also can you confirm that this script works? I'm pretty sure the default environment variable name is `GITHUB_TOKEN`?

2024-08-23 11:32 UTC, 0x4007 approved these changes

2024-08-23 11:33 UTC, 0x4007 commented
I am assuming that the bot auth token acts the same as a PAT so it should work but technically this is untested.

2024-08-23 11:33 UTC, merged