Close Issues from Archived Repositories
devpool-directory/devpool-directory pull request #1425
Opened 2024-09-03 12:04 UTC by jordan-ae

Resolves [#32](https://github.com/ubiquity/devpool-directory-bounties/issues/32)

2024-09-03 12:08 UTC, 0x4007 commented on helpers/github.ts
> +  if (projectIssue.repository?.archived === true) return;
projectIssue.repository?

dont use ?

catch and throw an error

2024-09-03 12:13 UTC, jordan-ae commented on helpers/github.ts
> +  if (projectIssue.repository?.archived === true) return;
Do you mean something like this?
```
  if (!projectIssue.repository || projectIssue.repository.archived === true) {
    if (!projectIssue.repository) {
      throw new Error("Repository data is missing for the project issue.");
    }
    return;
  }
```

2024-09-08 12:44 UTC, jordan-ae commented
@0x4007 is this okay?

2024-09-13 21:17 UTC, jordan-ae commented
@0x4007 can I please get a review here?

2024-09-14 03:27 UTC, 0x4007 requested changes
You need to post a QA test before approval.

2024-09-14 03:27 UTC, 0x4007 commented on helpers/github.ts
> +    if (!projectIssue.repository) {
Checking the same condition twice doesn't make sense you need to refactor your logic

2024-09-14 03:27 UTC, 0x4007 commented on tests/devpool-issue-handler.test.ts
> +          archived: false,
All of your changes only check for archived false. Is that right?

2024-09-20 22:30 UTC, closed without merging